version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/var/www
    ports:
      - 80:80
    environment:
      - DB_HOST=db
      - DB_DATABASE=your-database-name
      - DB_USERNAME=your-database-username
      - DB_PASSWORD=your-database-password
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your-database-root-password
      MYSQL_DATABASE: your-database-name
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db_data:
